import React, { ComponentProps } from 'react';
import { renderToString } from 'react-dom/server';
import serialize from 'serialize-javascript';
import TestApp from '../client/TestApp';
import PreviewTestApp from '../client/PreviewTestApp';
import IsolatedTestApp from '../client/IsolatedTestApp';
import RicosTestApp from '../client/RicosTestApp';
import { ChunkExtractor } from '@loadable/server';
import path from 'path';
import RichContentApp from '../../../../examples/main/shared/RichContentApp';

import '../client/app.css';

export default function renderer() {
  return (req, res) => {
    const [componentId, fixtureName = 'empty'] = req.path.replace(/^\/|\/$/g, '').split(/\/(.+)/);
    const compMap = {
      rce: TestApp,
      'rce-isolated': IsolatedTestApp,
      rcp: PreviewTestApp,
      ricos: RicosTestApp,
    };
    if (Object.keys(compMap).indexOf(componentId) === -1) {
      return res.status(404).send(`Component for ${componentId} not found`);
    }

    const isMobile = req.query.mobile === '';
    const locale = req.query.hebrew === '' ? 'he' : 'en';
    const seoMode = req.query.seoMode === '' ? {} : undefined;
    const testAppConfig = JSON.parse(req.query.testAppConfig || '{}');
    const props: ComponentProps<typeof RichContentApp> = {
      isMobile,
      locale,
      seoMode,
      testAppConfig,
    };

    try {
      props.initialState = require(`../../../tests/fixtures/${fixtureName}.json`);
    } catch (error) {
      console.log(error); //eslint-disable-line no-console
      return res.status(404).send(`Fixture ${fixtureName} not found`);
    }

    const App = compMap[componentId];

    // // This is the stats file generated by webpack loadable plugin
    const nodeStats = path.resolve(__dirname, '../../dist/server/loadable-stats.json');
    const webStats = path.resolve(__dirname, '../../dist/client/loadable-stats.json');

    // // We create an extractor from the statsFile
    const nodeExtractor = new ChunkExtractor({ statsFile: nodeStats, entrypoints: ['renderer'] });
    const webExtractor = new ChunkExtractor({ statsFile: webStats, entrypoints: ['index'] });

    // // Wrap your application using "collectChunks"
    const jsx = webExtractor.collectChunks(<RichContentApp app={App} mode={'test'} {...props} />);
    // // Render your application
    const html = renderToString(jsx);
    // // You can now collect your script tags
    const scriptTags = webExtractor.getScriptTags();
    // // And you can even collect your style tags (if you use "mini-css-extract-plugin")
    const styleTags = nodeExtractor.getStyleTags();
    res.render('index', {
      html,
      compId: componentId,
      initialState: props.initialState,
      isMobile,
      locale,
      testAppConfig,
      serialize,
      scriptTags,
      styleTags,
    });
  };
}
