import {
  RICOS_DIVIDER_TYPE,
  DIVIDER_TYPE,
  IMAGE_TYPE,
  RICOS_IMAGE_TYPE,
  GALLERY_TYPE,
  RICOS_GALLERY_TYPE,
  FILE_UPLOAD_TYPE,
  RICOS_FILE_TYPE,
  GIPHY_TYPE,
  RICOS_GIPHY_TYPE,
  VIDEO_TYPE,
  RICOS_VIDEO_TYPE,
  RICOS_POLL_TYPE,
} from 'wix-rich-content-common';

import {
  TIPTAP_BUTTON_TYPE,
  TIPTAP_DIVIDER_TYPE,
  TIPTAP_IMAGE_TYPE,
  TIPTAP_GALLERY_TYPE,
  TIPTAP_FILE_TYPE,
  TIPTAP_GIF_TYPE,
  TIPTAP_HTML_TYPE,
  TIPTAP_VIDEO_TYPE,
  TIPTAP_COLLAPSIBLE_LIST_TYPE,
  TIPTAP_LINK_PREVIEW_TYPE,
  TIPTAP_MAP_TYPE,
  TIPTAP_APP_EMBED_TYPE,
  TIPTAP_POLL_TYPE,
  TIPTAP_TABLE_TYPE,
  TIPTAP_EMBED_TYPE,
  TIPTAP_EXTERNAL_TYPE,
} from 'ricos-content';

import { Node_Type } from 'ricos-schema';

export const TIPTAP_TYPE_TO_RICOS_TYPE = {
  [TIPTAP_DIVIDER_TYPE]: RICOS_DIVIDER_TYPE,
  [TIPTAP_IMAGE_TYPE]: RICOS_IMAGE_TYPE,
  [TIPTAP_GALLERY_TYPE]: RICOS_GALLERY_TYPE,
  [TIPTAP_FILE_TYPE]: RICOS_FILE_TYPE,
  [TIPTAP_GIF_TYPE]: RICOS_GIPHY_TYPE,
  [TIPTAP_VIDEO_TYPE]: RICOS_VIDEO_TYPE,
  [TIPTAP_POLL_TYPE]: RICOS_POLL_TYPE,
  text: 'text',
};

export const TO_TIPTAP_TYPE = {
  [RICOS_DIVIDER_TYPE]: TIPTAP_DIVIDER_TYPE,
  [DIVIDER_TYPE]: TIPTAP_DIVIDER_TYPE,
  [RICOS_IMAGE_TYPE]: TIPTAP_IMAGE_TYPE,
  [IMAGE_TYPE]: TIPTAP_IMAGE_TYPE,
  [GALLERY_TYPE]: TIPTAP_GALLERY_TYPE,
  [RICOS_GALLERY_TYPE]: TIPTAP_GALLERY_TYPE,
  [FILE_UPLOAD_TYPE]: TIPTAP_FILE_TYPE,
  [RICOS_FILE_TYPE]: TIPTAP_FILE_TYPE,
  [GIPHY_TYPE]: TIPTAP_GIF_TYPE,
  [RICOS_GIPHY_TYPE]: TIPTAP_GIF_TYPE,
  [VIDEO_TYPE]: TIPTAP_VIDEO_TYPE,
  [RICOS_VIDEO_TYPE]: TIPTAP_VIDEO_TYPE,
};

export const FROM_RICOS_NODE_TYPE_TO_TIPTAP_TYPE = {
  [Node_Type.BUTTON]: TIPTAP_BUTTON_TYPE,
  [Node_Type.DIVIDER]: TIPTAP_DIVIDER_TYPE,
  [Node_Type.FILE]: TIPTAP_FILE_TYPE,
  [Node_Type.GALLERY]: TIPTAP_GALLERY_TYPE,
  [Node_Type.GIF]: TIPTAP_GIF_TYPE,
  [Node_Type.HTML]: TIPTAP_HTML_TYPE,
  [Node_Type.IMAGE]: TIPTAP_IMAGE_TYPE,
  [Node_Type.COLLAPSIBLE_LIST]: TIPTAP_COLLAPSIBLE_LIST_TYPE,
  [Node_Type.LINK_PREVIEW]: TIPTAP_LINK_PREVIEW_TYPE,
  [Node_Type.MAP]: TIPTAP_MAP_TYPE,
  [Node_Type.APP_EMBED]: TIPTAP_APP_EMBED_TYPE,
  [Node_Type.VIDEO]: TIPTAP_VIDEO_TYPE,
  [Node_Type.POLL]: TIPTAP_POLL_TYPE,
  [Node_Type.TABLE]: TIPTAP_TABLE_TYPE,
  [Node_Type.EMBED]: TIPTAP_EMBED_TYPE,
  [Node_Type.EXTERNAL]: TIPTAP_EXTERNAL_TYPE,
};
