import {
  RICOS_DIVIDER_TYPE,
  DIVIDER_TYPE,
  IMAGE_TYPE,
  RICOS_IMAGE_TYPE,
  GALLERY_TYPE,
  RICOS_GALLERY_TYPE,
  FILE_UPLOAD_TYPE,
  RICOS_FILE_TYPE,
  GIPHY_TYPE,
  RICOS_GIPHY_TYPE,
  VIDEO_TYPE,
  RICOS_VIDEO_TYPE,
  RICOS_POLL_TYPE,
  POLL_TYPE,
} from 'wix-rich-content-common';

import {
  TIPTAP_DIVIDER_TYPE,
  TIPTAP_IMAGE_TYPE,
  TIPTAP_GALLERY_TYPE,
  TIPTAP_FILE_TYPE,
  TIPTAP_GIF_TYPE,
  TIPTAP_VIDEO_TYPE,
  TIPTAP_POLL_TYPE,
} from 'ricos-content';

export const TIPTAP_TYPE_TO_RICOS_TYPE = {
  [TIPTAP_DIVIDER_TYPE]: RICOS_DIVIDER_TYPE,
  [TIPTAP_IMAGE_TYPE]: RICOS_IMAGE_TYPE,
  [TIPTAP_GALLERY_TYPE]: RICOS_GALLERY_TYPE,
  [TIPTAP_FILE_TYPE]: RICOS_FILE_TYPE,
  [TIPTAP_GIF_TYPE]: RICOS_GIPHY_TYPE,
  [TIPTAP_VIDEO_TYPE]: RICOS_VIDEO_TYPE,
  [TIPTAP_POLL_TYPE]: RICOS_POLL_TYPE,
  text: 'text',
};

export const TO_TIPTAP_TYPE = {
  [RICOS_DIVIDER_TYPE]: TIPTAP_DIVIDER_TYPE,
  [DIVIDER_TYPE]: TIPTAP_DIVIDER_TYPE,
  [RICOS_IMAGE_TYPE]: TIPTAP_IMAGE_TYPE,
  [IMAGE_TYPE]: TIPTAP_IMAGE_TYPE,
  [GALLERY_TYPE]: TIPTAP_GALLERY_TYPE,
  [RICOS_GALLERY_TYPE]: TIPTAP_GALLERY_TYPE,
  [FILE_UPLOAD_TYPE]: TIPTAP_FILE_TYPE,
  [RICOS_FILE_TYPE]: TIPTAP_FILE_TYPE,
  [GIPHY_TYPE]: TIPTAP_GIF_TYPE,
  [RICOS_GIPHY_TYPE]: TIPTAP_GIF_TYPE,
  [VIDEO_TYPE]: TIPTAP_VIDEO_TYPE,
  [RICOS_VIDEO_TYPE]: TIPTAP_VIDEO_TYPE,
  [RICOS_POLL_TYPE]: TIPTAP_POLL_TYPE,
  [POLL_TYPE]: TIPTAP_POLL_TYPE,
};
