export const EXPERIMENTS = [
  { name: 'detachCommandsFromEditor', scope: 'ricos' },
  { name: 'tiptapEditor', scope: 'ricos' },
  { name: 'TiptapMockToolbar', scope: 'ricos' },
  { name: 'newFormattingToolbar', scope: 'ricos' },
  { name: 'newSettingsModals', scope: 'ricos' },
  { name: 'newVideoVerticalAndSocialModals', scope: 'ricos' },
  { name: 'fixedTabSize', scope: 'ricos' },
  { name: 'forceIframeSandboxDomain', scope: 'ricos' },
  { name: 'useSeo', scope: 'wixRicos' },
  { name: 'spoilerInSettings', scope: 'ricos' },
  { name: 'removeUsmFromImageUrls', scope: 'ricos' },
  { name: 'lazyImagesAndIframes', scope: 'ricos' },
  { name: 'anchorScrollWithoutScrollIntoView', scope: 'ricos' },
  { name: 'useSrcSet', scope: 'ricos' },
  { name: 'normalizePoll', scope: 'ricos' },
  { name: 'optimizeFullScreenModal', scope: 'ricos' },
  { name: 'useFilePluginAutoDownloadLinkRef', scope: 'ricos' },
  { name: 'enableFilePluginPDFViewer', scope: 'ricos' },
  { name: 'encAutoImageUrls', scope: 'ricos' },
  { name: 'useUploadContext', scope: 'ricos' },
  { name: 'imageFigureCaption', scope: 'ricos' },
  { name: 'removeRichContentSchemaNormalizer', scope: 'ricos' },
];
