export { default as InfoIcon } from './InfoIcon';
export { default as CloseIcon } from './CloseIcon';
export { default as MoreIcon } from './MoreIcon';
export { default as ClearIcon } from './ClearIcon';
export { default as SearchIcon } from './SearchIcon';
export { default as DropdownArrowIcon } from './DropdownArrowIcon';
export { default as CheckIcon } from './CheckIcon';
export { default as ErrorIcon } from './ErrorIcon';
export { default as PlusIcon } from './PlusIcon';
export { default as DownloadIcon } from './DownloadIcon';
export { default as PauseIcon } from './PauseIcon';
export { default as PlayIcon } from './PlayIcon';
export { default as SoundMutedIcon } from './SoundMutedIcon';
export { default as SoundIcon } from './SoundIcon';
export { default as MediaReplaceIcon } from './MediaReplaceIcon';
export { default as ContextMenuIcon } from './ContextMenuIcon';
export { default as PlaybackIcon } from './PlaybackIcon';
export { default as ReplaceIcon } from './ReplaceIcon';
export { default as TrashIcon } from './TrashIcon';
export { default as SoundCloudIcon } from './SoundCloudIcon';
export { default as SpotifyIcon } from './SpotifyIcon';
export { default as LoaderIcon } from './LoaderIcon';
export { default as CirclePlusIcon } from './CirclePlusIcon';

//need to import from plugin-commons
// export { default as AlignCenterIcon } from './AlignCenterIcon';
// export { default as BackArrowIcon } from './BackArrowIcon';
// export { default as HeightIcon } from './HeightIcon';
// export { default as PluginSettingsIcon } from './PluginSettingsIcon';
// export { default as SizeBestFitIcon } from './SizeBestFitIcon';
// export { default as SizeFullWidthIcon } from './SizeFullWidthIcon';
// export { default as SizeLargeIcon } from './SizeLargeIcon';
// export { default as SizeMediumIcon } from './SizeMediumIcon';
// export { default as SizeOriginalIcon } from './SizeOriginalIcon';
// export { default as SizeSmallCenterIcon } from './SizeSmallCenterIcon';
// export { default as SizeSmallIcon } from './SizeSmallIcon';
// export { default as SizeSmallLeftIcon } from './SizeSmallLeftIcon';
// export { default as SizeSmallRightIcon } from './SizeSmallRightIcon';
// export { default as SpoilerButtonIcon } from './SpoilerButtonIcon';
// export { default as TrashIcon } from './TrashIcon';
// export { default as WidthIcon } from './WidthIcon';
// export { default as EditIcon } from './EditIcon';
// export { default as RTLIcon } from './RTLIcon';
// export { default as LTRIcon } from './LTRIcon';
// export { default as LoaderIcon } from './LoaderIcon';
// export { default as HashtagIcon } from './HashtagIcon';
