import type { RicosExtension } from 'ricos-tiptap-types';
import { createCommandsConfig } from '../../core-commands';
import {
  createDraftConfig,
  createFocusConfig,
  createHistoryConfig,
  createStylesConfig,
  createBulletedList,
  createBold,
  createParagraph,
  createItalic,
  createUnderline,
  createText,
  createDoc,
  createListItem,
  createBlockquote,
  createOrderedList,
  createTrailingNode,
  createLink,
  createPlaceholder,
  createFontSize,
  createUniqueId,
  createTextAlign,
  createTextDirection,
} from 'wix-tiptap-extensions';

export const coreConfigs = ({ placeholder }) => [
  createDraftConfig(),
  createHistoryConfig(),
  createStylesConfig(),
  createFocusConfig(),
  createCommandsConfig(),
  createBulletedList(),
  createBold(),
  createParagraph(),
  createItalic(),
  createUnderline(),
  createText(),
  createDoc(),
  createListItem(),
  createBlockquote(),
  createOrderedList(),
  createTrailingNode(),
  // TODO: pass config?
  createLink({}),
  createPlaceholder({ placeholder }),
  createFontSize(),
  createUniqueId(),
  createTextAlign(),
  createTextDirection(),
];
