/*eslint-disable */
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
const lodash_1 = require('lodash');

const content = {
  blocks: [
    {
      key: 'ponh',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'c8l3b',
      text: 'Sommaire. ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 9,
          style: '18',
        },
        {
          offset: 0,
          length: 9,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'mk5c',
      text: 'Introduction.  ',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 13,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '5ca6k',
      text: 'Marque.',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '4co6c',
      text: 'Adresse.',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '6rmo9',
      text: 'Découpe du Bois.  ',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 16,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'cddlq',
      text: 'Menuiserie de proximité.  ',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 24,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'den8r',
      text: ' Conclusion. ',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 12,
          style: '18',
        },
        {
          offset: 0,
          length: 1,
          style: 'BOLD',
        },
        {
          offset: 11,
          length: 1,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '4b8o8',
      text: 'I - Introduction.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 17,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'covgl',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '6eqdd',
      text:
        "Le magasin offre un service commercial convivial, les employés sont à notre service et c'est très agréable.",
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 107,
          style: '{"FG":"#050505"}',
        },
        {
          offset: 0,
          length: 107,
          style: '{"BG":"#ffffff"}',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '9eerl',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '6cca7',
      text: 'II - Marque.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 12,
          style: '{"FG":"#050505"}',
        },
        {
          offset: 0,
          length: 12,
          style: '{"BG":"#ffffff"}',
        },
        {
          offset: 0,
          length: 12,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '7qhic',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 0,
        },
      ],
      data: {},
    },
    {
      key: '7mgkl',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'f1s0m',
      text: 'III - Adresse.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 14,
          style: '18',
        },
        {
          offset: 0,
          length: 14,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '8rapi',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'ae8uk',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 1,
        },
      ],
      data: {},
    },
    {
      key: '4nkhu',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 2,
        },
      ],
      data: {},
    },
    {
      key: 'e5po9',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '8plgs',
      text: 'IV - Découpe du Bois.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 21,
          style: '18',
        },
        {
          offset: 0,
          length: 21,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '1f76g',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '1ttjl',
      text: 'IV - I Les différents matériaux. ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 32,
          style: '17',
        },
        {
          offset: 0,
          length: 32,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'a7bjj',
      text: 'Médium : carton très peu cher. Pour des martyrs par exemple.  ',
      type: 'unordered-list-item',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 60,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'a5kp4',
      text: 'Contreplaqué intérieur : 3 mm 5 mm 10 mm 12 mm 15 mm 18 mm...  ',
      type: 'unordered-list-item',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 61,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '73ruf',
      text: 'Contreplaqué extérieur : 3 mm 5 mm 10 mm 12 mm 15 mm 18 mm... ',
      type: 'unordered-list-item',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 61,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '2b45j',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '42o2o',
      text: ' ',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 1,
          key: 3,
        },
      ],
      data: {},
    },
    {
      key: 'fpk1o',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '3ean6',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '4j3ss',
      text: 'IV- II Fonctionnement.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 22,
          style: '17',
        },
        {
          offset: 0,
          length: 22,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'eg4mk',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'fjvab',
      text: 'Le prix dépend de la surface. La découpe avec une scie à panneaux est gratuite.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 79,
          style: '18',
        },
        {
          offset: 46,
          length: 19,
          style: 'UNDERLINE',
        },
      ],
      entityRanges: [
        {
          offset: 46,
          length: 19,
          key: 4,
        },
      ],
      data: {},
    },
    {
      key: '6fv74',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '7lu56',
      text: 'IV - III La découpe de votre bois.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 34,
          style: '18',
        },
        {
          offset: 0,
          length: 34,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'be60u',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'f9obl',
      text:
        "Il est très pratique d'acheter son contreplaqué avec un dimensionnement que vous choisissez, cela évite de sortir la scie circulaire à la maison.",
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '7ev58',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'ais8r',
      text:
        'Il est également peu onéreux de faire découper ses panneaux de sapin. Vous amenez votre bois chez bricorama, vous payez 0,5 euros et vous avez votre bois découpé avec précision avec la scie à panneaux. Attention! largeur et longueur minimum : 20 cm.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '4bp4g',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'c8ulg',
      text: 'V - Menuiserie de proximité.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 28,
          style: '18',
        },
        {
          offset: 0,
          length: 28,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'b3iq8',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'an30s',
      text: 'V - I Le petit matériel.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 24,
          style: '17',
        },
        {
          offset: 0,
          length: 24,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '3bfne',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '2vlof',
      text: "Pour l'achat de machines, préférez Leroy merlin ou Castorama,",
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 61,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '69een',
      text: 'Le petit matériel ne nécessite pas un déplacement à Brest.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 58,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '9leo6',
      text: 'Mon coup de cœur pour les serres joints bricorama.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 50,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '7nh0n',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '6lm1e',
      text: 'V - II Les tasseaux.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 20,
          style: '17',
        },
        {
          offset: 0,
          length: 19,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '1i6t3',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '20dg',
      text: 'Un choix correct pour les tasseaux, 2 Mètre 20, en résineux, différents profils.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 80,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'c9ji2',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'fagkk',
      text: 'VI - Conclusion.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 16,
          style: '18',
        },
        {
          offset: 0,
          length: 16,
          style: 'BOLD',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '3fv8p',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'etgqr',
      text:
        "L'atelier découpe est indispensable à un menuisier amateur et relativement peu onéreux.",
      type: 'unordered-list-item',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 87,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: 'fq2hr',
      text: "La carte de fidélité, gratuite, offre un bon achat de 5 euros dès 250 euros d'achat.",
      type: 'unordered-list-item',
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 84,
          style: '18',
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: '8sn2o',
      text: ' ',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '9lala',
      text: '#Magasin',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
  ],
  entityMap: {
    '0': {
      type: 'wix-draft-plugin-image',
      mutability: 'IMMUTABLE',
      data: {
        config: {
          alignment: 'center',
          size: 'small',
          showTitle: true,
          showDescription: true,
          key: '7mgkl',
          textWrap: 'wrap',
        },
        src: {
          id: 'cf0579_5702a88937e540a5a83f99728dc71cd6~mv2.jpg',
          original_file_name: 'cf0579_5702a88937e540a5a83f99728dc71cd6~mv2.jpg',
          file_name: 'cf0579_5702a88937e540a5a83f99728dc71cd6~mv2.jpg',
          width: 468,
          height: 358,
        },
        metadata: {
          alt: '',
        },
      },
    },
    '1': {
      type: 'wix-draft-plugin-html',
      mutability: 'IMMUTABLE',
      data: {
        srcType: 'html',
        src:
          '<font size="4">\n      <b>BRICORAMA PLOUDALMEZEAU</b><br>\n      <img src="https://lh4.ggpht.com/Tr5sntMif9qOPrKV_UVl7K8A_V3xQDgA7Sw_qweLUFlg76d_vGFA7q1xIKZ6IcmeGqg=w300"\n\n        height="25" width="25">Zi De Kéruscat, 29830 Ploudalmézeau.<br>\n      ☎ 02 29 05 04 05<br>\n    </font>',
        config: {
          alignment: 'center',
          width: 740,
          height: 125,
          textWrap: 'wrap',
        },
      },
    },
    '2': {
      type: 'wix-draft-plugin-html',
      mutability: 'IMMUTABLE',
      data: {
        config: {
          alignment: 'center',
          width: 740,
          height: '250',
          key: '4m66',
          textWrap: 'wrap',
        },
        src:
          '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2641.7594486275584!2d-4.669655684284918!3d48.537841531176866!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x481698d3b0da1ce3%3A0x689febbc405dcb54!2sBricorama+Ploudalmezeau!5e0!3m2!1sfr!2sfr!4v1517065116322" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>',
        srcType: 'html',
      },
    },
    '3': {
      type: 'wix-draft-plugin-image',
      mutability: 'IMMUTABLE',
      data: {
        config: {
          alignment: 'center',
          size: 'small',
          showTitle: true,
          showDescription: true,
          key: '2b45j',
          textWrap: 'wrap',
        },
        src: {
          id: 'cf0579_8333ed0988bb4d2999b231c92eb4eb43~mv2_d_4288_3216_s_4_2.jpg',
          original_file_name: 'cf0579_8333ed0988bb4d2999b231c92eb4eb43~mv2_d_4288_3216_s_4_2.jpg',
          file_name: 'cf0579_8333ed0988bb4d2999b231c92eb4eb43~mv2_d_4288_3216_s_4_2.jpg',
          width: 4288,
          height: 3216,
        },
        metadata: {
          alt: '',
        },
      },
    },
    '4': {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'https://www.monatelierbois.com/post/la-scie-%C3%A0-panneaux-bricorama',
        target: '_top',
        rel: 'noopener noreferrer',
      },
    },
  },
  documentStyle: {},
  VERSION: '8.63.7',
  ID: 'ba61a37a-fb85-40b2-8a17-de7440ae84bd',
};
/* eslint-disable no-console */
/* eslint-disable fp/no-loops */
/* eslint-disable no-unreachable */
const migrateSchema_1 = require('ricos-content/libs/migrateSchema');
const r = (0, migrateSchema_1.fromDraft)(content, { ignoreUnsupportedValues: true });
const c = (0, migrateSchema_1.toDraft)(r);
console.log(JSON.stringify(c));

//e9119df9-0137-4ff0-9e7f-a04f7b64e151
