export const RESOLVERS_IDS = {
  ALWAYS_VISIBLE: 'ALWAYS_VISIBLE',
  IS_TEXT_IN_SELECTION: 'IS_TEXT_IN_SELECTION',
  IS_TEXT_CONTAINS_BOLD: 'IS_TEXT_CONTAINS_BOLD',
  IS_TEXT_CONTAINS_ITALIC: 'IS_TEXT_CONTAINS_ITALIC',
  IS_TEXT_CONTAINS_UNDERLINE: 'IS_TEXT_CONTAINS_UNDERLINE',
  IS_TEXT_CONTAINS_QUOTE: 'IS_TEXT_CONTAINS_QUOTE',
  IS_TEXT_CONTAINS_CODE_BLOCK: 'IS_TEXT_CONTAINS_CODE_BLOCK',
  IS_TEXT_CONTAINS_ORDERED_LIST: 'IS_TEXT_CONTAINS_ORDERED_LIST',
  IS_TEXT_CONTAINS_UNORDERED_LIST: 'IS_TEXT_CONTAINS_UNORDERED_LIST',
  IS_TEXT_CONTAINS_SPOILER: 'IS_TEXT_CONTAINS_SPOILER',
};
