export const RESOLVERS_IDS = {
  ALWAYS_VISIBLE: 'ALWAYS_VISIBLE',
  IS_TEXT_CONTAINS_BOLD: 'IS_TEXT_CONTAINS_BOLD',
  IS_TEXT_CONTAINS_ITALIC: 'IS_TEXT_CONTAINS_ITALIC',
  IS_TEXT_CONTAINS_UNDERLINE: 'IS_TEXT_CONTAINS_UNDERLINE',
};
