export const EXPERIMENTS = [
  { name: 'newFormattingToolbar', scope: 'ricos' },
  { name: 'tiptapEditor', scope: 'ricos' },
  { name: 'newVideoModal', scope: 'ricos' },
  { name: 'newSocialAndVerticalEmbedModal', scope: 'ricos' },
  { name: 'forceIframeSandboxDomain', scope: 'ricos' },
  { name: 'useSeo', scope: 'wixRicos' },
  { name: 'tableCellsLimit', scope: 'ricos', input: [100, 200, 300, 500, 1000] },
  { name: 'spoilerInSettings', scope: 'ricos' },
  { name: 'removeUsmFromImageUrls', scope: 'ricos' },
  { name: 'lazyImagesAndIframes', scope: 'ricos' },
  { name: 'anchorScrollWithoutScrollIntoView', scope: 'ricos' },
  { name: 'useSrcSet', scope: 'ricos' },
  { name: 'pastedFilesSupport', scope: 'ricos' },
];
