import { Node_Type } from 'ricos-schema';
export declare const HEADER_BLOCK: Readonly<{
    ONE: string;
    TWO: string;
    THREE: string;
    FOUR: string;
    FIVE: string;
    SIX: string;
    PARAGRAPH: string;
}>;
export declare const DEFAULT_TITLE_HEADINGS: string[];
export declare const DEFAULT_HEADINGS: string[];
export declare const BLOCK_TYPES: readonly string[];
export declare const WRAP = "wrap";
export declare const NO_WRAP = "nowrap";
export declare const UNSTYLED = "unstyled";
export declare const BLOCKQUOTE = "blockquote";
export declare const NUMBERED_LIST_TYPE = "ordered-list-item";
export declare const BULLET_LIST_TYPE = "unordered-list-item";
export declare const HEADINGS_TYPE = "headings";
export declare const isListType: (type: string) => boolean;
export declare const LINK_BUTTON_TYPE = "wix-draft-plugin-link-button";
export declare const ACTION_BUTTON_TYPE = "wix-draft-plugin-action-button";
export declare const CODE_BLOCK_TYPE = "code-block";
export declare const DIVIDER_TYPE = "wix-draft-plugin-divider";
export declare const EMOJI_TYPE = "wix-draft-plugin-emoji";
export declare const FILE_UPLOAD_TYPE = "wix-draft-plugin-file-upload";
export declare const GALLERY_TYPE = "wix-draft-plugin-gallery";
export declare const GIPHY_TYPE = "wix-draft-plugin-giphy";
export declare const HASHTAG_TYPE = "wix-draft-plugin-hashtag";
export declare const HEADERS_MARKDOWN_TYPE = "wix-draft-plugin-headers-markdown";
export declare const HTML_TYPE = "wix-draft-plugin-html";
export declare const IMAGE_TYPE = "wix-draft-plugin-image";
export declare const IMAGE_TYPE_LEGACY = "IMAGE";
export declare const INDENT_TYPE = "wix-rich-content-plugin-indent";
export declare const LINE_SPACING_TYPE = "line-spacing";
export declare const HEADINGS_DROPDOWN_TYPE = "wix-rich-content-plugin-headings";
export declare const SPOILER_TYPE = "wix-rich-content-plugin-spoiler";
export declare const COLLAPSIBLE_LIST_TYPE = "wix-rich-content-plugin-collapsible-list";
export declare const EXTERNAL_LINK_TYPE = "wix-draft-plugin-external-link";
export declare const LINK_TYPE = "LINK";
export declare const CUSTOM_LINK_TYPE = "ricos-plugin-custom-link";
export declare const LINK_PREVIEW_TYPE = "wix-draft-plugin-link-preview";
export declare const MAP_TYPE = "wix-draft-plugin-map";
export declare const EXTERNAL_MENTIONS_TYPE = "wix-draft-plugin-external-mentions";
export declare const MENTION_TYPE = "mention";
export declare const SOUND_CLOUD_TYPE = "wix-draft-plugin-sound-cloud";
export declare const TEXT_COLOR_TYPE = "wix-rich-content-text-color";
export declare const TEXT_HIGHLIGHT_TYPE = "wix-rich-content-text-highlight";
export declare const UNDO_REDO_TYPE = "wix-rich-content-undo-redo";
export declare const APP_EMBED_TYPE = "wix-draft-plugin-vertical-embed";
export declare const VERTICAL_EMBED_TYPE = "wix-draft-plugin-vertical-embed";
export declare const VIDEO_TYPE = "wix-draft-plugin-video";
export declare const VIDEO_TYPE_LEGACY = "VIDEO-EMBED";
export declare const POLL_TYPE = "wix-draft-plugin-poll";
export declare const TABLE_TYPE = "wix-rich-content-plugin-table";
export declare const ANCHOR_TYPE = "ANCHOR";
export declare const PREVIEW = "PREVIEW";
export declare const UNSUPPORTED_BLOCKS_TYPE = "unsupported-blocks";
export declare const EMBED_TYPE = "EMBED";
export declare const EXTERNAL = "EXTERNAL";
export declare const RICOS_COLLAPSIBLE_LIST_TYPE = "ricos-collapsible-list";
export declare const RICOS_ACTION_BUTTON_TYPE = "ricos-action-button";
export declare const RICOS_CODE_BLOCK_TYPE = "ricos-code-block";
export declare const RICOS_DIVIDER_TYPE = "ricos-divider";
export declare const RICOS_EMOJI_TYPE = "ricos-emoji";
export declare const RICOS_FILE_TYPE = "ricos-file";
export declare const RICOS_GALLERY_TYPE = "ricos-gallery";
export declare const RICOS_GIPHY_TYPE = "ricos-giphy";
export declare const RICOS_HASHTAG_TYPE = "ricos-hashtag";
export declare const RICOS_HEADERS_MARKDOWN_TYPE = "ricos-headers-markdown";
export declare const RICOS_HEADINGS_DROPDOWN_TYPE = "ricos-heading-dropdown";
export declare const RICOS_HEADING = "ricos-heading";
export declare const RICOS_HTML_TYPE = "ricos-html";
export declare const RICOS_IMAGE_TYPE = "ricos-image";
export declare const RICOS_INDENT_TYPE = "ricos-indent";
export declare const RICOS_LINE_SPACING_TYPE = "ricos-line-spacing";
export declare const RICOS_LINK_BUTTON_TYPE = "ricos-link-button";
export declare const RICOS_LINK_PREVIEW_TYPE = "ricos-link-preview";
export declare const RICOS_MAP_TYPE = "ricos-map";
export declare const RICOS_POLL_TYPE = "ricos-poll";
export declare const RICOS_SOUND_CLOUD_TYPE = "ricos-sound-cloud";
export declare const RICOS_SPOILER_TYPE = "ricos-spoiler";
export declare const RICOS_TABLE_TYPE = "ricos-table";
export declare const RICOS_TEXT_COLOR_TYPE = "ricos-text-color";
export declare const RICOS_TEXT_HIGHLIGHT_TYPE = "ricos-text-highlight";
export declare const RICOS_UNDO_REDO_TYPE = "ricos-undo-redo";
export declare const RICOS_VERTICAL_EMBED_TYPE = "ricos-vertical-embed";
export declare const RICOS_VIDEO_TYPE = "ricos-video";
export declare const RICOS_ANCHOR_TYPE = "ricos-anchor";
export declare const RICOS_COLOR_TYPE = "ricos-color";
export declare const RICOS_LINK_TYPE = "ricos-link";
export declare const RICOS_MENTION_TYPE = "ricos-mention";
export declare const RICOS_FONT_SIZE_TYPE = "ricos-font-size";
export declare const RICOS_BOLD_TYPE = "ricos-bold";
export declare const RICOS_ITALIC_TYPE = "ricos-italic";
export declare const RICOS_EXTERNAL_LINK_TYPE = "ricos-external-link";
export declare const RICOS_EXTERNAL_MENTION_TYPE = "ricos-external-mention";
export declare const TIPTAP_DIVIDER_TYPE = "divider";
export declare const TIPTAP_IMAGE_TYPE = "image";
export declare const TIPTAP_GALLERY_TYPE = "gallery";
export declare const TIPTAP_FILE_TYPE = "file";
export declare const TIPTAP_GIF_TYPE = "gif";
export declare const TIPTAP_VIDEO_TYPE = "video";
export declare const TIPTAP_LINK_PREVIEW_TYPE = "linkPreview";
export declare const RICOS_NODE_TYPE_TO_DATA_FIELD: {
    readonly BUTTON: "buttonData";
    readonly DIVIDER: "dividerData";
    readonly FILE: "fileData";
    readonly GALLERY: "galleryData";
    readonly GIF: "gifData";
    readonly HTML: "htmlData";
    readonly IMAGE: "imageData";
    readonly COLLAPSIBLE_LIST: "collapsibleListData";
    readonly LINK_PREVIEW: "linkPreviewData";
    readonly MAP: "mapData";
    readonly APP_EMBED: "appEmbedData";
    readonly VIDEO: "videoData";
    readonly POLL: "pollData";
    readonly TABLE: "tableData";
    readonly TABLE_CELL: "tableCellData";
    readonly PARAGRAPH: "paragraphData";
    readonly LIST_ITEM: "paragraphData";
    readonly HEADING: "headingData";
    readonly CODE_BLOCK: "codeBlockData";
    readonly BLOCKQUOTE: "paragraphData";
    readonly EMBED: "embedData";
    readonly EXTERNAL: "externalData";
};
//# sourceMappingURL=consts.d.ts.map